apiVersion: apps/v1
kind: Deployment
metadata:
  name: core-api
  namespace: lms
  labels:
    app: core-api
    component: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: core-api
  template:
    metadata:
      labels:
        app: core-api
        component: backend
    spec:
      containers:
      - name: core-api
        image: ${DOCKER_REGISTRY}/lms/core-api:${VERSION}
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        resources:
          limits:
            cpu: "1"
            memory: "1Gi"
          requests:
            cpu: "500m"
            memory: "512Mi"
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: password
        - name: POSTGRES_HOST
          value: postgres
        - name: POSTGRES_DB
          value: lms_db
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: kafka:9092
        - name: REDIS_HOST
          value: redis
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: jwt-secret
              key: token
        - name: LOG_LEVEL
          value: "INFO"
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: core-api
  namespace: lms
  labels:
    app: core-api
    component: backend
spec:
  selector:
    app: core-api
  ports:
  - port: 8000
    targetPort: 8000
    name: http
  type: ClusterIP